In [1]:
# pytorch는 추천 시스템 만들때 필요한 기능이다

In [3]:
# pytorch = 3차원 이상의 배열을 다룰 때 사용하는 라이브러리
import torch

In [4]:
# 1. tensor란? tensor 만들기

In [5]:
# 하나의 torch 만들기.
V_data = [1., 2., 3.]
V = torch.Tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [6]:
# 매트릭스 만들기
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.Tensor(M_data)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [7]:
# 3차원 텐서 만들기
T_data = [[1., 2., 3.], [4., 5., 6], [7., 8., 9.]]
T = torch.Tensor(T_data)
print(T)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [8]:
# torch.ones : tensor를 size에 맞게 1로 채운다
a = torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [9]:
# torch.zeros : tensor를 size에 맞게 0로 채운다
b = torch.zeros(3)
print(b)

tensor([0., 0., 0.])


In [10]:
# 초기화되면서 현재 메모리에 존재하는 값
x = torch.empty(5,3)
print(x)

tensor([[3.4242e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [11]:
# rand값 넣기
rand = torch.rand(5,3)
print(rand)

tensor([[0.7554, 0.0996, 0.0598],
        [0.3886, 0.5720, 0.7984],
        [0.3978, 0.0914, 0.4162],
        [0.0478, 0.4289, 0.8199],
        [0.1593, 0.1963, 0.5429]])


In [12]:
# torch.rand : 랜덤 숫자로 tensor를 채운다
rand_points = torch.rand(4, dtype=torch.double)
print(rand_points)

rand_points_2 = torch.rand(2,3,dtype=torch.float)
print(rand_points_2)

tensor([0.6206, 0.2021, 0.1222, 0.8305], dtype=torch.float64)
tensor([[0.2626, 0.6639, 0.0673],
        [0.4953, 0.9477, 0.7229]])


In [13]:
# 행렬 사이즈
print(rand_points_2.size())

torch.Size([2, 3])


In [15]:
# 2. Indexing Tensors
temp = torch.Tensor([0,1,2,3,4,5,6,7])

print(temp[:]) # tensor element 전체
print(temp[1:4]) # 1부터 4까지
print(temp[1:]) # 1부터 끝까지
print(temp[:4]) # 0부터 4까지
print(temp[-1]) # 맨뒤 한 개 값
print(temp[1:6:2]) # index 1과 6사이의 원소 출력 (2단계씩 증가)


tensor([0., 1., 2., 3., 4., 5., 6., 7.])
tensor([1., 2., 3.])
tensor([1., 2., 3., 4., 5., 6., 7.])
tensor([0., 1., 2., 3.])
tensor(7.)
tensor([1., 3., 5.])


In [16]:
temp2 = torch.Tensor([[1,2,3],[4,5,6]])

print(temp2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [18]:
# 3. tensor element types
## 
float_points = torch.ones(5,2,dtype=torch.float32)
int_points = torch.zeros(3,dtype=torch.int64)

print(float_points)
print(int_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([0, 0, 0])


In [19]:
# default - float
default_points = torch.Tensor([2,2])
print(default_points)

tensor([2., 2.])


In [20]:
# find out dtype
print(float_points.dtype)
print(int_points.dtype)
print(default_points.dtype)

torch.float32
torch.int64
torch.float32


In [22]:
# other fomrs of specifying dtype
to_int_1 = float_points.int()
print(to_int_1)

# 'to' check
to_int_2 = float_points.to(torch.int64)
print(to_int_2)

to_float_1 = int_points.float()
print(to_float_1.dtype)

to_float_2 = int_points.to(dtype=torch.float16)
print(to_float_2.dtype)

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])
torch.float32
torch.float16


In [23]:
# 4. the tensor api
# 5. tensor shape and reshape

In [25]:
# shape : 텐서 사이즈 보여주기
a = torch.Tensor([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [26]:
# size()
print(a.size())

torch.Size([2, 3])


In [27]:
# reshape : 주어진 shape로 original tensor에서 데이터를 가져와서 reshape한다
a_reshape=a.reshape(3,2)
print(a_reshape)
print(a_reshape.shape)

a_reshape2=a.reshape(-1,2)
print(a_reshape2)
print(a_reshape2.shape)



tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])


In [28]:
a_no_reshape = a.reshape(4,3)
# element 갯수가 맞지 않음  

RuntimeError: ignored

In [31]:
# view : returns a new tensor with the same data
x = torch.randn(4,4)
print(x.size())

y = x.view(16)
print(y.size())


z = x.view(-1, 8)
print(z.size())
# 행렬 변환 하는 기능

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [32]:
print(y)

tensor([-0.5919,  1.5801, -0.3612,  0.7630, -1.1418, -0.1669, -0.4676,  0.9408,
        -0.5453, -0.0214, -1.3081,  0.8759, -1.2567, -0.2709,  0.3413,  0.6110])


In [33]:
print(z)

tensor([[-0.5919,  1.5801, -0.3612,  0.7630, -1.1418, -0.1669, -0.4676,  0.9408],
        [-0.5453, -0.0214, -1.3081,  0.8759, -1.2567, -0.2709,  0.3413,  0.6110]])


In [35]:
# 6. transpose
## view와는 다른 개념이다
x  = torch.randn(1)
print(x)
print(torch.t(x))

tensor([1.9493])
tensor([1.9493])


In [36]:
y = torch.randn(3)
print(y)
print(y.t())

tensor([ 0.4638, -2.1665,  0.3162])
tensor([ 0.4638, -2.1665,  0.3162])


In [37]:
z = torch.randn(2,3)
print(z)
print(torch.t(z))

tensor([[ 0.5058, -1.5435, -0.8122],
        [ 0.9882,  1.5629,  0.7853]])
tensor([[ 0.5058,  0.9882],
        [-1.5435,  1.5629],
        [-0.8122,  0.7853]])


In [38]:
## torch.transpose
w = torch.randn(2, 3)
print(w)
print(torch.transpose(w,0,1))

tensor([[-0.3489, -0.2849,  0.6074],
        [ 0.9551,  1.0380, -0.4154]])
tensor([[-0.3489,  0.9551],
        [-0.2849,  1.0380],
        [ 0.6074, -0.4154]])


In [39]:
# more complex case
real_example = torch.randn(64, 128, 768)
print(real_example.shape)
transpose = torch.transpose(real_example, 1,2)
print(transpose.shape)

torch.Size([64, 128, 768])
torch.Size([64, 768, 128])


In [41]:
# 7. operations example
x = torch.ones(1,2)
print(x)
y = torch.ones(5,3)
print(y)

tensor([[1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [42]:
print(x+y)
# x와 y는 사이즈가 맞지 않아 연산이 안된다

RuntimeError: ignored

In [44]:
y = torch.ones(5,2)
print(x+y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])


In [45]:
# 더하기 연산
print(x+y)
print(torch.add(x,y))

## 빈 공간 만들어서 연산한 후 집어넣기
result = torch.empty(5, 2)
torch.add(x, y, out=result)

print(y.add_(x))

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])


In [46]:
## refernce : movie tensors  (gpgpu 활용하기)
### 런타임 < 런타임 유형 변경 < 하드웨어 가속기 < gpu 로 선택하면 gpgpu 사용 가능하다

torch.cuda.is_available()

# 주의! 런타임 유형 변경하면, colab 세션이 초기화됨

False

In [4]:
## gpgpu
import torch
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
print(points_gpu)

points = torch.randn(2,2)
points_gpu = points.to(device='cuda')

print(points_gpu)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')
tensor([[ 0.0409, -0.1701],
        [-0.2123, -0.5126]], device='cuda:0')


In [6]:
# 8. numpy interpretability
## tensor --> numpy array
points = torch.ones(3,4)
points_np = points.numpy()

print(points_np)
type(points_np)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


numpy.ndarray

In [7]:
# numpy array to tensor
points = torch.from_numpy(points_np)
print(points)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [9]:
# 9. save and load tensors
print(points)
torch.save(points, '.points_temp.t')


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
