# 개요
- numpy/pandas 친해지기
- torch로 vector, matrix 등 만들어보기


In [3]:
import warnings
warnings.filterwarnings("ignore")
# 버전 차이로 생기는 오류는 무시하는 것이다.

In [4]:
import numpy as np

리스트, 행렬 선언

In [12]:
a = [1,2, 3]
b = ['a', 'b', 'c']
c = [['a'], ['a','b'], ['a','c']]

print (a)
print (b)
print (c)

[1, 2, 3]
['a', 'b', 'c']
[['a'], ['a', 'b'], ['a', 'c']]


In [7]:
a = np.array([1,2, 3])
b = np.array(['a', 'b', 'c'])
c = np.array([['a'], ['a','b'], ['a','c']])

print (a)
print (b)
print (c)

[1 2 3]
['a' 'b' 'c']
[list(['a']) list(['a', 'b']) list(['a', 'c'])]


In [13]:
# appendfh item 추가하기
#c.append('new item')
c.append(['new item'])

print (c)

[['a'], ['a', 'b'], ['a', 'c'], ['new item']]


In [17]:
# 배열 또는 행렬에 1로 채우기
print(np.ones((1,5)))
print(np.ones((2,3)))

[[1. 1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# 배열 또는 행렬에 0로 채우기
print(np.zeros((1,5)))
print(np.zeros((2,3)))

[[0. 0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# 배열 또는 행렬 안에 순차적으로 증가하는 리스트 만들기
print(np.arange(10))
print(np.arange(3, 7, dtype=np.float))
print(np.arange(3, 7, 2))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5]


In [25]:
# 행렬 선언하기
mat1 = np.array([[1,2,3],[4,5,6]])

# random으로 matrix 만들기
mat2 = np.random.randint(low=1, high=10, size=(3,2))
mat3 = np.random.rand(3,2)

print(mat1)
print(mat2)
print(mat3)


[[1 2 3]
 [4 5 6]]
[[1 8]
 [8 8]
 [2 7]]
[[0.85236058 0.90423549]
 [0.48843569 0.77266385]
 [0.70511257 0.38879966]]


In [28]:
# 리스트 인덱싱(indexing) & 슬라이싱(slicing)
#indexing
a = [1,3,5,7,9,11]
print(a)

print(a[2], a[5], a[-1])

[1, 3, 5, 7, 9, 11]
5 11 11


In [31]:
# slicing
b= [2,4,6,8,10]
print(b[2:])
print(b[:2])
print(b[:])

[6, 8, 10]
[2, 4]
[2, 4, 6, 8, 10]


In [33]:
# numpy의 reshape(pytorch의 view와 비교)
# (row, col)
matt1 = np.random.rand(6,3)
print(matt1)

[[0.33168586 0.85913014 0.62195975]
 [0.15767386 0.07727356 0.71972504]
 [0.59797132 0.16730903 0.8281012 ]
 [0.14123067 0.64382609 0.65508103]
 [0.41432323 0.65193856 0.81270469]
 [0.87221708 0.45118063 0.51891783]]


In [38]:
# -1: all
print(matt1.reshape(1,-1).shape)
print(matt1.reshape(1,-1))
print("---------------------------------")
print(matt1.reshape(-1,1).shape)
print(matt1.reshape(-1,1))

(1, 18)
[[0.33168586 0.85913014 0.62195975 0.15767386 0.07727356 0.71972504
  0.59797132 0.16730903 0.8281012  0.14123067 0.64382609 0.65508103
  0.41432323 0.65193856 0.81270469 0.87221708 0.45118063 0.51891783]]
---------------------------------
(18, 1)
[[0.33168586]
 [0.85913014]
 [0.62195975]
 [0.15767386]
 [0.07727356]
 [0.71972504]
 [0.59797132]
 [0.16730903]
 [0.8281012 ]
 [0.14123067]
 [0.64382609]
 [0.65508103]
 [0.41432323]
 [0.65193856]
 [0.81270469]
 [0.87221708]
 [0.45118063]
 [0.51891783]]


In [39]:
print(matt1.reshape(2,9).shape)
print(matt1.reshape(2,9))

(2, 9)
[[0.33168586 0.85913014 0.62195975 0.15767386 0.07727356 0.71972504
  0.59797132 0.16730903 0.8281012 ]
 [0.14123067 0.64382609 0.65508103 0.41432323 0.65193856 0.81270469
  0.87221708 0.45118063 0.51891783]]


In [ ]:
print(matt1.reshape(2,5).shape)
print(matt1.reshape(2,5))
# matt1는 3,6으로 구성된 행렬이므로 에러가 발생함

In [40]:
# tensor 형태로 나타내기
print(matt1.reshape(3,2,3).shape)
print(matt1.reshape(3,2,3))

(3, 2, 3)
[[[0.33168586 0.85913014 0.62195975]
  [0.15767386 0.07727356 0.71972504]]

 [[0.59797132 0.16730903 0.8281012 ]
  [0.14123067 0.64382609 0.65508103]]

 [[0.41432323 0.65193856 0.81270469]
  [0.87221708 0.45118063 0.51891783]]]


In [42]:
# matrix or tensor 형태에서도 slicing 가능하다.
matt2 = np.arange(24).reshape(-1,4)
print(matt2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [48]:
print(matt2[:1,:3])
print(matt2[3,0:2])

matt2[:1,:3]


[[0 1 2]]
[12 13]


array([[0, 1, 2]])

In [47]:
matt2[3,0:2]

array([12, 13])

In [49]:
# 사칙연산
x = np.array([[1,3,5], [7,9,11], [13,15,17]])
y = np.array([[2,4,6], [8,10,12], [14,16, 18]])

print(x)
print(y)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [50]:
# add
x + y

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [52]:
x-y


array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [53]:
x*y


array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [54]:

x/y

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [56]:
# 제곱
print(x **2 )
print(np.power(x, 2))

[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]
[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]


In [57]:
# 내적구하기
np.dot(x,y)

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [58]:
# 제곱근
np.sqrt(x)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [59]:
# more on matrix operation
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

z1 * z2

ValueError: ignored

In [61]:
# transpose
print(z1.T)

[[2]
 [2]
 [2]]


In [63]:
z3 = np.array([1,2,3])

print(np.dot(z1, z3))

[12]


In [ ]:
# random
