In [2]:
############################
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [3]:
###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [4]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
#print(아이리스)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [5]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [6]:
###########################
# 2. 모델의 구조를 만듭니다 (히든레이어 사용 X)
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [9]:
###########################
# 2. 모델의 구조를 만듭니다 (히든레이어 1개 사용)
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [11]:
###########################
# 2. 모델의 구조를 만듭니다 (히든레이어 멀티 사용)
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [12]:
 ###########################
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0567 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0472 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0627 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0545 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0429 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0437 - accuracy: 0.9867
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0458 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0543 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0546 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0466 - accuracy: 0.9800


In [ ]:
###########################
# 4. 모델을 이용합니다
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])


[[9.9950886e-01 4.9117289e-04 5.3278487e-08]
 [9.9777728e-01 2.2222458e-03 5.0057690e-07]
 [9.9896693e-01 1.0327806e-03 2.0400981e-07]
 [9.9692565e-01 3.0734115e-03 9.6306928e-07]
 [9.9959677e-01 4.0322932e-04 4.3640185e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

[[2.7168755e-07 1.0055436e-01 8.9944535e-01]
 [6.7347656e-07 1.9431677e-01 8.0568254e-01]
 [1.1857300e-06 2.1282969e-01 7.8716916e-01]
 [1.9180645e-07 7.3208757e-02 9.2679101e-01]
 [2.3556163e-06 2.5501886e-01 7.4497873e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:

###########################
# weights & bias 출력
print(model.get_weights())

[array([[ 1.0435044 ,  0.294481  , -0.7332861 ],
       [ 2.9719255 ,  0.24911287, -0.8012833 ],
       [-3.9022746 , -0.17529976,  1.092739  ],
       [-4.3330665 , -1.4214922 ,  2.207451  ]], dtype=float32), array([ 1.4345133,  1.3660737, -1.3459892], dtype=float32)]
